version: '3.7'

services:
    api:
        build: ./app
        command: python manage.py runserver --settings=api.development.dev 0.0.0.0:8000
        volumes:
            - ./app/:/usr/src/app/
        ports:
            - 8000:8000
        #env_file:
            #- ./.env
        environment:
            - POSTGRES_DB=db
            - POSTGRES_USER=${SQL_USER}
            - POSTGRES_PASSWORD=${SQL_PASSWORD}
            - POSTGRES_DB=${SQL_DATABASE}
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=${SQL_USER}
            - POSTGRES_PASSWORD=${SQL_PASSWORD}
            - POSTGRES_DB=${SQL_DATABASE}
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin-dev
        depends_on:
            - db
        ports:
            - 5051:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PG_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PG_PASSWORD}
        restart: always

volumes:
    postgres_data:
