version: '3.7'

services:
    api:
        build: ./app
        command: python manage.py runserver --settings=api.settings.development 0.0.0.0:8000
        volumes:
            - ./app/:/usr/src/app/
        ports:
            - 8000:8000
        #env_file:
            #- ./.env
        environment:
            - SQL_HOST=db
            - SQL_DATABASE=${SQL_DATABASE}
            - SQL_USER=${SQL_USER}
            - SQL_PASSWORD=${SQL_PASSWORD}
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=${SQL_DATABASE}
            - POSTGRES_USER=${SQL_USER}
            - POSTGRES_PASSWORD=${SQL_PASSWORD}
    prometheus:
        image: prom/prometheus:v2.14.0
        volumes:
            - ./prometheus/:/etc/prometheus/
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - 9090:9090
    grafana:
        image: grafana/grafana:6.5.2
        ports:
            - 3060:3000

volumes:
    postgres_data:
