version: '3.7'

services:
    api:
        build: ./app
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./app/:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./.env_dev
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=strech_user
            - POSTGRES_PASSWORD=strech2020
            - POSTGRES_DB=strech_db
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin-dev
        depends_on:
            - db
        ports:
            - 5051:80
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@ngelrojasp.com
            PGADMIN_DEFAULT_PASSWORD: admin2020
        restart: always

volumes:
    postgres_data:
