global:
    scrape_interval: 15s
    evaluation_interval: 15s

rule_files:
    # no-files

scrape_configs:
- job_name: monitoring
  static_configs:
      - targets:
          - 127.0.0.1:9090
- job_name: monitoring_api
  static_configs:
      - targets:
          - 127.0.0.1:8000
